import {LitElement,html,css,nothing,render as litRender} from 'lit';import {customElement,property,state} from 'lit/decorators.js';import type {CardConfig,Hass,MachineState} from './types';import {defaults} from './types';import {runtimeFor,claimOwner,releaseOwner} from './runtime';import {audioKey,isPaired,pair,unpair} from './device';
@customElement('baby-monitor-kiosk-card') export class Card extends LitElement{
 @property({attribute:false}) hass?:Hass;@state() private machineState:MachineState='IDLE';@state() private muted=true;private config!:CardConfig;private runtime?:ReturnType<typeof runtimeFor>;private unsubscribe?:()=>void;private camera?:any;private portal?:HTMLDivElement;private cameraSignature='';private currentBrightness=100;private currentVolume=100;
 static styles=css`:host{display:block;min-height:1px}.stage{position:fixed;inset:0;z-index:2147483000;background:#000;display:grid;place-items:center}.stage>*:first-child{width:100%;height:100%}.controls{position:absolute;left:50%;bottom:max(24px,env(safe-area-inset-bottom));transform:translateX(-50%);display:flex;gap:18px}.controls button{width:68px;height:68px;border:0;border-radius:50%;font-size:28px;background:#111c;color:white}.preload{position:fixed;width:2px;height:2px;opacity:.01;pointer-events:none;overflow:hidden;left:-4px;top:-4px}.debug{position:fixed;z-index:2147483001;top:8px;left:8px;background:#000b;color:#fff;padding:8px;font:14px monospace}.idle{font-size:12px;color:var(--secondary-text-color)}`;
 static getConfigElement(){return document.createElement('baby-monitor-kiosk-card-editor')} static getStubConfig(){return{type:'custom:baby-monitor-kiosk-card',camera:'camera.babykamer',sound_sensor:'binary_sensor.babykamer_geluid',preload:true,silence_duration:5,kiosk:{device_bound:true}}}
 setConfig(c:CardConfig){if((!c.camera&&!c.stream)||!c.sound_sensor)throw Error('camera or stream, and sound_sensor are required');const nextId=c.id??`${c.camera??c.stream}|${c.sound_sensor}`;if(this.config&&this.configId!==nextId){this.unsubscribe?.();releaseOwner(this.configId,this);this.portal?.remove();this.portal=undefined;this.camera=undefined;this.cameraSignature=''}this.config={...defaults,...c};this.id=this.configId;this.currentBrightness=c.companion?.active_brightness??100;this.currentVolume=c.companion?.active_volume??100;const stored=c.audio?.remember_state===false?null:localStorage.getItem(audioKey(this.configId));this.muted=stored===null?(c.audio?.default_muted??false):stored==='true';this.connectRuntime();if(this.isConnected){this.ensureCamera();this.configureCamera()}}
 private get configId(){return this.config?.id??`${this.config?.camera??this.config?.stream}|${this.config?.sound_sensor}`}
 private connectRuntime(){this.unsubscribe?.();this.runtime=runtimeFor(this.config);this.unsubscribe=this.runtime.subscribe(s=>{this.machineState=s;this.requestUpdate();if(claimOwner(this.configId,this)){if(s==='ACTIVE')this.companion(true);if(s==='IDLE'||s==='MANUAL_COOLDOWN')this.companion(false)}})}
 connectedCallback(){super.connectedCallback();if(this.config){this.connectRuntime();this.ensureCamera();this.configureCamera()}} disconnectedCallback(){super.disconnectedCallback();this.unsubscribe?.();this.unsubscribe=undefined;this.portal?.remove();this.portal=undefined;releaseOwner(this.configId,this)}
 updated(){if(this.hass)this.runtime?.update(this.hass);this.ensureCamera();if(this.camera)this.camera.hass=this.hass;this.syncPortal()}
 private cameraConfig(){return{type:'custom:webrtc-camera',...(this.config.stream?{url:this.config.stream}:{entity:this.config.camera}),muted:this.muted,controls:true}}
 private configureCamera(){const config=this.cameraConfig(),signature=JSON.stringify(config);if(this.camera&&signature!==this.cameraSignature){this.camera.setConfig?.(config);this.cameraSignature=signature}}
 private ensureCamera(){if(!this.isConnected||this.camera||!this.config||!this.eligible()||!claimOwner(this.configId,this))return;this.camera=document.createElement('webrtc-camera');this.camera.style.cssText='display:block;width:100%;height:100%;object-fit:contain';this.configureCamera()}
 private eligible(){return this.config.kiosk?.enabled!==false&&(this.config.kiosk?.device_bound===false||isPaired(this.configId))&&(!this.config.kiosk?.allowed_user_ids?.length||!!this.hass?.user&&this.config.kiosk.allowed_user_ids.includes(this.hass.user.id))}
 private active(){return this.config.auto_open!==false&&this.eligible()&&(this.machineState==='ACTIVE'||this.machineState==='SILENCE_TIMER')}
 private toggleMute(){this.muted=!this.muted;if(this.config.audio?.remember_state!==false)localStorage.setItem(audioKey(this.configId),String(this.muted));this.configureCamera();this.requestUpdate()}
 private async companion(active:boolean){const service=this.config.companion?.notify_service;if(!service||!this.eligible()||!this.hass)return;const brightness=active?this.config.companion?.active_brightness:this.config.companion?.idle_brightness;const volume=active?this.config.companion?.active_volume:this.config.companion?.idle_volume;const commands=[] as {message:string;data?:Record<string,unknown>}[];if(active&&this.config.companion?.screensaver!==false)commands.push({message:'kiosk_hide_screensaver'});if(brightness!=null)commands.push({message:'kiosk_set_brightness',data:{level:brightness}});if(volume!=null)commands.push({message:'kiosk_set_volume',data:{volume}});if(!active&&this.config.companion?.screensaver!==false)commands.push({message:'kiosk_show_screensaver'});for(const command of commands)try{await this.hass.callService('notify',service,command)}catch(e){if(this.config.debug)console.warn('[baby-monitor] Companion command failed',e)}}
 private async kioskLevel(kind:'brightness'|'volume',delta:number){const service=this.config.companion?.notify_service;if(!service||!this.hass)return;const value=Math.max(0,Math.min(100,(kind==='brightness'?this.currentBrightness:this.currentVolume)+delta));if(kind==='brightness')this.currentBrightness=value;else this.currentVolume=value;const message=kind==='brightness'?'kiosk_set_brightness':'kiosk_set_volume';const data=kind==='brightness'?{level:value}:{volume:value};try{await this.hass.callService('notify',service,{message,data})}catch(e){if(this.config.debug)console.warn('[baby-monitor] Companion level command failed',e)}}
 private syncPortal(){if(!this.camera||!claimOwner(this.configId,this))return;if(!this.portal){this.portal=document.createElement('div');this.portal.dataset.babyMonitorKiosk=this.configId;document.body.append(this.portal)}const show=this.active(),preload=this.config.preload!==false&&this.eligible();this.portal.style.cssText=show?'position:fixed;inset:0;z-index:2147483000;background:#000;display:grid;place-items:center;':'position:fixed;width:2px;height:2px;opacity:.01;pointer-events:none;overflow:hidden;left:-4px;top:-4px;';litRender(show||preload?html`<style>.cam{width:100%;height:100%}.controls{position:absolute;left:50%;bottom:max(24px,env(safe-area-inset-bottom));transform:translateX(-50%);display:flex;gap:12px;flex-wrap:wrap;justify-content:center}.controls button{width:68px;height:68px;border:0;border-radius:50%;font-size:25px;background:#111c;color:#fff}</style><div class=cam>${this.camera}</div>${show?html`<div class=controls>${this.config.controls?.brightness?html`<button aria-label="Helderheid lager" @click=${()=>this.kioskLevel('brightness',-20)}>☀−</button><button aria-label="Helderheid hoger" @click=${()=>this.kioskLevel('brightness',20)}>☀+</button>`:nothing}${this.config.controls?.volume?html`<button aria-label="Volume lager" @click=${()=>this.kioskLevel('volume',-20)}>−🔊</button><button aria-label="Volume hoger" @click=${()=>this.kioskLevel('volume',20)}>+🔊</button>`:nothing}${this.config.controls?.mute!==false?html`<button aria-label=${this.muted?'Geluid aan':'Geluid uit'} @click=${()=>this.toggleMute()}>${this.muted?'🔇':'🔊'}</button>`:nothing}${this.config.controls?.close!==false?html`<button aria-label="Sluiten" @click=${()=>this.runtime?.close()}>✕</button>`:nothing}</div>`:nothing}`:nothing,this.portal)}
 private togglePair(){isPaired(this.configId)?unpair(this.configId):pair(this.configId);if(isPaired(this.configId))this.ensureCamera();this.requestUpdate()}
 render(){if(!this.config)return nothing;const sensor=this.hass?.states[this.config.sound_sensor]?.state??'?';const paired=isPaired(this.configId);return html`${this.config.show_setup?html`<ha-card class="setup"><div><b>Baby Monitor Kiosk</b><div>Dit apparaat is ${paired?'gekoppeld':'niet gekoppeld'}.</div></div><button @click=${()=>this.togglePair()}>${paired?'Ontkoppelen':'Koppel dit apparaat'}</button></ha-card>`:nothing}${!this.active()&&this.config.preload===false?html`<span class=idle>Baby monitor gereed</span>`:nothing}${this.config.debug?html`<div class=debug>state=${this.machineState} | value=${sensor} | on≥${this.config.sound_threshold_db??'-'} | off≤${this.config.sound_reset_db??'-'} | timer=${Math.ceil((this.runtime?.remainingMs()??0)/1000)}s | kiosk=${this.eligible()} | preload=${this.config.preload!==false&&this.eligible()}</div>`:nothing}`}
}
